name = "docbuild"
reservoir = false
version = "0.1.0"
packagesDir = "../.lake/packages"

[[require]]
name = "InfinityCategories"
path = "../"

[[require]]
name = "doc-gen4"
scope = "leanprover"
rev = "v4.23.0"
